### ISSUE TITLE
OpenMP package is slightly slower

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#112]
I just ran a couple of tests with OpenMP, and surprisingly, it was slower. 60 images that were processing at `7.6s` total, became `9.1s` with OpenMP.

Most of our operations consisted of taking arrays of data and using `GetPixelsUnsafe().SetPixels()` or getting the Array from `GetPixelsUnsafe()` and then populating our arrays.

`MagickImage.Equalize()` is almost twice as slow.

**Comment by daxpandhi** [comment]
Version `7.0.7.300` without OpenMP performs perfectly like the previous version (total time of 7.6s in the test).

**Comment by dlemstra** [comment]
I wonder if you should see a performance improvement when you use the GetPixelsUnsafe method. I don't think these methods use OpenMP. It seems that you are copying the pixels to and from your array. Maybe we could add `Copy` methods to the PixelCollection to make this easier/faster for you. What would your requirements be?

I wonder if the OpenMP has a startup penalty because the C++ redistributable is dynamically linked in that build. What happens when you execute the same action a couple times in a for loop?

**Comment by daxpandhi** [comment]
Good point.

I'll run a more extended barrage of tests, and see if we can get better samples.

**Comment by dlemstra** [comment]
@daxpandhi Did you have time to research this yet?

**Comment by daxpandhi** [comment]
Sorry - I forgot to do this. Ran tests on the most recent build and it is performing normally, ie, no performance problems in OpenMP.
