### ISSUE TITLE
Issue with DrawingText onto image / only on Linux Docker ASP.net

### ISSUE THREAD

**Issue by feuermark** [dlemstra/Magick.NET#1127]
```
blazor.server.js:21 [2022-02-11T17:01:46.123Z] Error: ImageMagick.MagickDrawErrorException: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4462
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception) in /_/src/Magick.NET/Exceptions/MagickExceptionHelper.cs:line 18
   at ImageMagick.NativeHelper.CheckException(IntPtr exception) in /_/src/Magick.NET/Native/NativeHelper.cs:line 27
   at ImageMagick.DrawingWand.NativeDrawingWand.Render() in /_/src/Magick.NET/Native/Drawables/DrawingWand.cs:line 1236
   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables) in /_/src/Magick.NET/MagickImage.cs:line 2740
   at ImageMagick.MagickImage.Draw(IDrawable[] drawables) in /_/src/Magick.NET/MagickImage.cs:line 2727
   at Clozeo_Uploader_1._0.Pages.EditActiveUser.SendWelcomeEmail() in /src/Pages/EditActiveUser.razor:line 217
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

Offending Code:
```
var Certificate = System.IO.File.ReadAllBytes($"{System.IO.Directory.GetCurrentDirectory()}{@"/wwwroot/images/Certificate.png"}");
var image = new MagickImage(Certificate);
image.Settings.FontPointsize = 40;
var drawables = new List<IDrawable>();
drawables.Add(new DrawableComposite(new MagickGeometry(350, 400, 404, 184), new MagickImage(Convert.FromBase64String(emailData.CompanyLogo))));
image.Draw(drawables);
image.Draw(new DrawableText(400, 1630, "CERTIFICATEDATA"));
//drawables = new List<IDrawable>();
//drawables.Add(new DrawableText(400, 1630, "CERTIFICATEDATA"));
```

It works and adds the DrawableComposite, but when I try to draw text it crashed.  

It works on the local Windows environment, but not on the linux Docker host.

Any help would be appreciated.

**Comment by dlemstra** [comment]
Did you install fontconfig in your container?

**Comment by AbdulAzeezC** [comment]
getting similar error here...
Getting this error on migrating to some latest Magick lib "exception: Magick: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4470"

currently we are using version imageMagick version 7.1.0-2
the same issue was not observed previously, as there is no change around this code since long time in our code.

some more inputs here we are trying to draw over an image & giving inputs like below (Note that some of the getter & setters are purely our application level.
If you can kindly help with the syntax of drawableText or something is got changed in between these versions prior to above mentioned version??

std::vectorMagick::Drawable aDrawList;
// font
aDrawList.push_back(DrawableFont(iImage.getDynAdFontFilePath()));
NGN_LOG_INFORMATION("Abdul Font related issue check "<< iImage.getDynAdFontFilePath()<<"\n"; // font color
aDrawList.push_back(DrawableFillColor(Color(iImage.getDynAdFontColor())));
// font size
aDrawList.push_back(DrawablePointSize(iImage.getDynAdFontSize()));
// text
const double aDX=BTB_Utils::convert<double, string>(iImage.getDynAdLocationX());
const double aDY=BTB_Utils::convert<double, string>(iImage.getDynAdLocationY());
aDrawList.push_back(DrawableText(aDX, aDY , iPriceCurrency));

**Comment by dlemstra** [comment]
You are reporting something in the wrong project? You are showing `C++` code.

**Comment by vitvitskyi** [comment]
Hello @dlemstra 

I'm getting the same error.

My Docker file is
`FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o out
RUN apt-get update && apt-get install -y libgdiplus libc6-dev
RUN apk add --no-cache msttcorefonts-installer && update-ms-fonts && fc-cache -f

RUN apt install libfreetype6-dev
RUN apt install libfontconfig1-dev
RUN apt install ghostscript

# install fontconfig
RUN apt-get update; apt-get install -y fontconfig

# refresh system font cache
RUN fc-cache -f -v

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /app
COPY --from=build /src/out .
ENTRYPOINT [ "dotnet", "/app/DockerNetExample.dll" ]`

c# code:
`
        [HttpPost]
        [Route("create")]
        public async Task<IActionResult> Create([FromForm] IFormFile file)
        {
            try
            {
                var oFileName = $"{DateTimeHelper.GetUniqFileName()}.webp";

                using (var memStream = new MemoryStream())
                {
                    file.CopyTo(memStream);
                    memStream.Position = 0;

                    using (var copyright = new MagickImage("xc:none", 350, 150))
                    {
                        copyright.Draw(new Drawables()
                            .FillColor(new MagickColor("grey"))
                            .Gravity(Gravity.Center)
                            .Rotation(-45)
                            .FontPointSize(15)
                            .Text(10, 10, "Watermark"));

                        using (var image = new MagickImage())
                        {
                            image.Read(memStream);
                            image.Format = MagickFormat.WebP;
                            image.Quality = 30;
                            image.Tile(copyright, CompositeOperator.Over);
                            image.Write(memStream);

                            return File(image.ToByteArray(), "application/octet-stream", oFileName);
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return StatusCode(500, ex.Message);
            }
        }
`

**Comment by dlemstra** [comment]
Please open separate issues instead of hijacking another one. Going to lock this issue.
