### ISSUE TITLE
Cant convert to JPEG XL

### ISSUE THREAD

**Issue by danpetitt** [dlemstra/Magick.NET#1130]
### Description
Simple project file converting a JPEG to JPEG XL fails without exceptions.

### Steps to Reproduce
Simple .NET6 console app with following code and attached image(s) fails and exits with `Test.exe (process 2924) exited with code -1073741819` without any exception being thrown or caught:

```cs
using ImageMagick;

try
{
  var file = @"dakar-rally.jpg";
  var fileSave = @"dakar-rally.jxl";

  MagickNET.Initialize();

  using var image = new MagickImage( file );
  image.Write( fileSave, MagickFormat.Jxl );
}
catch( MagickException ex )
{
  Console.WriteLine( ex.ToString() );
}
catch( Exception ex )
{
  Console.WriteLine( ex.ToString() );
}
```

Tested with images:
[us.zip](https://github.com/dlemstra/Magick.NET/files/8056628/us.zip)
[dakar-rally.zip](https://github.com/dlemstra/Magick.NET/files/8056626/dakar-rally.zip)

### System Configuration

- Magick.NET version: 9.1.2
- Environment (Operating system, version and so on): Windows 11
- Additional information: Using Magick.Net.Core and Magick.Net-Q16-AnyCpu

**Comment by dlemstra** [comment]
Thanks for reporting this. I could not reproduce your issue with a local debug build but testing with the release build inside the NuGet package resulted in the same error that you are getting. This seems to be happening due to the switch of the build from VisualStudio 2019 to 2022. Some kind of release optimization of Visualstudio 2022 breaks the code and will always result in an exception.

I disable the optimization of `jpeg-xl` inside @ImageMagick and this seems to fix the build. Going to need to run some tests to verify that the new build works now and then publish a new release later this week to resolve this.

**Comment by danpetitt** [comment]
Thanks a lot for taking the time looking into this very tricky issue Dirk

**Comment by pindumb** [comment]
I also had problems with JXL conversion. Is this the error "JXL_CHECK: metadata_->color_encoding.IsGray() == c_current.IsGray()" or is this a different one?

See: https://gitlab.com/wg1/jpeg-xl/-/issues/70

**Comment by dlemstra** [comment]
That sounds like a different issue @pindumb. And can you try again with the latest release (10.0.0)? And if this is still not working then please open a new issue with an image that I can use to test this.

**Comment by pindumb** [comment]
> That sounds like a different issue @pindumb. And can you try again with the latest release (10.0.0)? And if this is still not working then please open a new issue with an image that I can use to test this.

The issue I had could be reproduced with ImageMagick alone (without Magick.NET). So maybe I wait for the next ImageMagick version.
