### ISSUE TITLE
Image loading with Magick.Net really slow

### ISSUE THREAD

**Issue by Brubning** [dlemstra/Magick.NET#120]
Hi, I'm doing some very basic image operations with Magick.NET Q8 x64 7.0.7.700. I'm replacing an existing system, and I had a complaint that the old system is way quicker. I mocked up a quick test, and the problem is in creating the MagickImage object.

The old system uses PresentationCore.dll BitmapDecoder to load the bitmap, get a frame and then query the meta data. 
My system uses MagickImage (loading from path, and from a byte array) to load the bitmap, then get the XmpProfile and query it.

In both instances, querying the Xmp data is very quick, but MagickImage is **way** slower to load the image than the BitmapDecoder. I time it, and instantiating a MagickImage takes around 115 milliseconds, but the BitmapDecoder does it in 2 milliseconds. That's a huge difference.

The image file is a 4MB jpg, and I'm using the same image in both instances.

Code sample of the comparison - loading the image to Magick.NET object (115 milliseconds):

            var start = DateTime.Now;
            using (var fs = new FileStream(_path, FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite))
            {
                var length = Convert.ToInt32(fs.Length);
                byte[] bytes = new byte[length];
                fs.Read(bytes, 0, length);

                var label = string.Empty;
                var magickImg = new MagickImage(bytes) {Format = MagickFormat.Jpeg};
            }
            
            var end = DateTime.Now;
            XmpResult.Text = (end - start).TotalMilliseconds.ToString(CultureInfo.InvariantCulture);

Loading the image using System.Media.Windows.Imaging (2 milliseconds):

            var start = DateTime.Now;
            using (var fs = new FileStream(_path, FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite))
            {
                var label = string.Empty;
                var bmp = BitmapDecoder.Create(fs, BitmapCreateOptions.None, BitmapCacheOption.Default);
                var f = bmp.Frames[0];
            }
            var end = DateTime.Now;
            BmpResult.Text = (end - start).TotalMilliseconds.ToString(CultureInfo.InvariantCulture);

**Comment by dlemstra** [comment]
Could you share the input image that you are using? The first time ImageMagick runs it will do some initialization so that might be causing the performance difference. I wonder what happens when you pass the stream directly to the constructor instead. And I wonder if the BitmapDecoder does some kind of lazy loading.

**Comment by Brubning** [comment]
The original image I was using was of someone else, so I tried it on a different picture - same result. I've attached an anonymous photo that shows the same result - 150 milliseconds for MagickImage, 5 for BitmapDecoder.

Also, included the XAML and XAML.cs files.

[Files.zip](https://github.com/dlemstra/Magick.NET/files/1424010/Files.zip)

Thanks

**Comment by dlemstra** [comment]
Looking at your code it might be sufficient to do this:
```
using (var magickImg = new MagickImage())
{
  magickImg.Ping(bytes);
}
```

When you `Ping` an image only the metadata is read and the pixels are not decoded. And you could also do `magickImg.Ping(fs)` instead of first copying it to a byte array. But I just found out that the `Ping` method does a `Read` instead for the `stream` overload. I will publish a new release to resolve that bug this weekend. For now you will need to do `magickImg.Ping(fs, null)`.

Your test image does not contain an XMP profile so I cannot test if the xmp profile is read when the image is pinged but I would expect it to be available. Can you let me know if it works?

**Comment by Brubning** [comment]
Thanks, I tried that with an image that does have an XMP profile, and it is lightning. Anywhere between 2 and 3.5 milliseconds.

![image](https://user-images.githubusercontent.com/28068804/32158917-f51094ae-bd42-11e7-92f3-7ab265250307.png)

Thanks for your help, awesome.

**Comment by Brubning** [comment]
Oh, quick additional note. The 2-3.5 milliseconds is if I open the image from a byte array. If I pass the file stream in directly, this goes down to 1-1.5 milliseconds.
