### ISSUE TITLE
MagickImage Progress event when reading SVG file

### ISSUE THREAD

**Issue by gralin** [dlemstra/Magick.NET#129]
If we have a reference to an instance of MagickImage we can use it's event to monitor progress of operations being performed. But what if creating of MagickImage instance itself takes a significant amount of time? See the snippet below:

```csharp
var stopwatch = new Stopwatch();
stopwatch.Start();

var imageSettings = new MagickReadSettings { Density = new Density(1200) };
var image = magickFactory.CreateImage("test.svg", imageSettings);

Console.WriteLine(stopwatch.Elapsed);
```

Above shows me 15s in console window. Any idea on how this could be monitored so that the progress bar in GUI doesn't get stuck?

**Comment by dlemstra** [comment]
What you normally could do is call `CreateImage` without any arguments and then call `Read` with those arguments. But you are reading an `SVG` file which is handled by an external library called `librsvg`. You might need to give it a try but I don't think you will get any feedback while the image is being decoded.

**Comment by gralin** [comment]
@dlemstra you are right, creating the image without arguments and then subscribing to ``Progress`` and calling ``Read`` makes no difference 😞

**Comment by dlemstra** [comment]
I don't think we can "fix" this because the majority of the loading is happening inside the librsvg library.

**Comment by federicomenaquintero** [comment]
Unfortunately librsvg has no API to report progress.  The best it lets you do is to have two stages: loading and rendering.

Even reporting progress during loading would be a bit tricky, since SVG files can reference other resources - there's no way, up front, of knowing actually how many bytes you'll need to parse for the complete SVG data and its referenced files.
