### ISSUE TITLE
Magick.NET-Q16-AnyCPU with Net.Core

### ISSUE THREAD

**Issue by rdcm** [dlemstra/Magick.NET#131]
Hi!

`Magick.NET-Q16-AnyCPU` perfect work in console net core app on win10 platform, but in docker conteiner with web api app i have this exception message: `"The type initializer for 'NativeMagickSettings' threw an exception."`

In your docs i find this: 
https://github.com/dlemstra/Magick.NET/blob/master/Documentation/CrossPlatform.md
```
When running the project it is possible that the following error occurs:

Unhandled Exception: System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception. --->
  System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q8-x64.Native.dll': The specified module could not be found.
```
but where can i find `/path/to/ImageMagick/libraries` ?

Nuget version - 7.2.1

**Comment by dlemstra** [comment]
That is the folder that contains the files `libMagickCore-7.*` and `libMagickWand-7.*`. I will update the documentation to clarify this.

**Comment by rdcm** [comment]
Ok, what i need to install except the nuget package for correct work with library?

**Comment by dlemstra** [comment]
Did you install ImageMagick as explained in the instructions?

**Comment by rdcm** [comment]
Which one documentation did you mean?

https://magick.codeplex.com/documentation
https://www.imagemagick.org/script/download.php

i tried something like this:

```
apt-get -y update
apt-get -y install wget
apt-get -y install make
apt-get -y install gcc

wget http://www.imagemagick.org/download/ImageMagick.tar.gz
tar -xvf ImageMagick.tar.gz
cd ImageMagick-7.* && ./configure && make && make install
ldconfig /usr/local/lib
```

`libMagickCore-7.*` and `libMagickWand-7.* ` located at `/usr/local/lib` 

set the environment variable

`LD_LIBRARY_PATH=/usr/local/lib`

but i still have exception 
`["The type initializer for 'NativeMagickSettings' threw an exception."]`

**Comment by dlemstra** [comment]
I meant this one: https://github.com/dlemstra/Magick.NET/blob/master/Documentation/CrossPlatform.md. What is the output of: `ldd Magick.NET-Q16-x64.Native.dll.so`?

**Comment by rdcm** [comment]
My problem solved, your documentation correct.

Several clarifications:

-export SOME_VAR - this method set env variable for single terminal instance, if you set set LD_LIBRARY_PATH in one terminal, but run app into other terminal, you will have exception like `DLL not found`

- `ldd Magick.NET-Q16-x64.Native.dll.so` should run from publish directory, for check shared libraries

- instead `make install ` better use something else `checkinstall` util, because your package manager does not know anything about installed package after make install


Do you have planned create docker images containing imagemagick?

**Comment by dlemstra** [comment]
I don't have plans to create a docker image that contains imagemagick. But it might be wise to add some installation instructions or maybe even a script that you can use in your docker image.

**Comment by ARUNVMVK** [comment]
Magical.NET-Q16-x86.Native.gz not found error...please help me

**Comment by NagaRajeshK** [comment]
I have facing the following issue. Please do find attached docker file. I am not able to make ImageMagick work in my docker.Works fine in my windows.I have added package reference in my .net core project     <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="7.15.0"/>

[Dockerfile.txt](https://github.com/dlemstra/Magick.NET/files/4018343/Dockerfile.txt)

[06:22:59 ERR] The type initializer for 'NativeMagickSettings' threw an exception.
System.DllNotFoundException: Unable to load shared library 'Magick.Native-Q16-x64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libMagick.Native-Q16-x64.dll: No such file or directory
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.NativeEnvironment.Initialize()
   at ImageMagick.Environment.Initialize()
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor()
   at ImageMagick.MagickSettings.NativeMagickSettings..ctor()
   at ImageMagick.MagickSettings..ctor()
   at ImageMagick.MagickImage..ctor()
   at ImageMagick.MagickImage..ctor(Byte[] data)
