### ISSUE TITLE
certain TIF pictures doesnt load

### ISSUE THREAD

**Issue by JoGrob** [dlemstra/Magick.NET#1310]
### Magick.NET version

12.2

### Environment (Operating system, version and so on)

Windows 10 x64 / ImageGlass 8.7.11.6 x64

### Description

Some TIF pictures doesnt load.
Error message see screenshot attached.
Sample TIF picture see attached.
![errormsg](https://user-images.githubusercontent.com/59739587/204460844-31c58c03-4b7f-4685-a486-26afc18b94fc.jpg)
[picture.zip](https://github.com/dlemstra/Magick.NET/files/10110528/picture.zip)

### Steps to Reproduce

Try to load attaches TIF picture.

**Comment by dlemstra** [comment]
The library that is being used to load tiff files reported an error because your file seems to be corrupt.

**Comment by JoGrob** [comment]
In my oppinion TIF picture isnt corrupt, because many (maybe almost all) other software can display the picture.
I have sucessfully tried Windwos snip&sketch, Windows Photo, Paintshop Pro, Honeyview and some others.

**Comment by dlemstra** [comment]
The library that we are using is very strict and those other program ignore invalid tags and skip them instead of reporting an error. You might be able to work around this with the `TiffReadDefines` and then include `34022` in the `IgnoreTags`. I haven't tested this myself so I don't know if this works.
