### ISSUE TITLE
CMYK to MagickColor Always returns white

### ISSUE THREAD

**Issue by sam-masscreations** [dlemstra/Magick.NET#1558]
### Magick.NET version

13.6.0

### Environment (Operating system, version and so on)

Magick.NET-Q16-AnyCPU

### Description

Trying to set True black for CMYK, the colour is always returning white event though properties are set.
![image](https://github.com/dlemstra/Magick.NET/assets/93202281/bc75a8da-1b99-4729-a24b-8451eb631213)

### Steps to Reproduce

```
var textImage = new MagickImage("xc:none", 1701, 2386);
textImage.ColorSpace = ColorSpace.CMYK;
var thisColor = new MagickColor(75, 68, 67, 90, 65535);
// Define draw settings for text
var drawables = new Drawables()
    // Set font properties
    .Font("fonts/aAntiCorona.ttf", FontStyleType.Normal, FontWeight.Normal, FontStretch.Normal)
    .FontPointSize(25)
    .FillColor(thisColor)
    .TextAlignment(textAlignment)
    // Specify the location and text to draw
    .Text(location.X, location.Y, text)
    // Set text gravity
    .Gravity(gravity);

// Draw the text on the image
drawables.Draw(textImage);
```

**Comment by dlemstra** [comment]
You are not providing the correct values but you did found a bug in ImageMagick that is specific to using CMYK colors in `Drawables`. Instead of `75` you will need to use `0.75 * Quantum.Max` to get the correct value. But due to a bug you are still getting an incorrect color. Yesterday I pushed a patch to the repository of ImageMagick to fix this issue. In the next release you will get the correct color when you provide the correct input values.

**Comment by sam-masscreations** [comment]
Hey @dlemstra  appreciate your time looking into this one for me! Do you have a rough time frame for next release, just so i can manage expectations of the project. 

thanks

**Comment by dlemstra** [comment]
I don't plan the next release, it happens when it happens. For sponsors I sometimes do an earlier release because they need a specific feature or bug fix. When do you need this?
