### ISSUE TITLE
EXIF Orientation was Changed when Call AutoOrient() and Save.

### ISSUE THREAD

**Issue by xucongli1989** [dlemstra/Magick.NET#1636]
### Magick.NET version

13.8

### Environment (Operating system, version and so on)

Windows 11 & .NET Framework 4.7

### Description

After I loaded an image that contained counterclockwise rotation, I called `AutoOrient()`, then I saved the image object to disk and found that the rotation EXIF had been lost. My understanding are:
1. The purpose of calling `AutoOrient()` is only to calculate the correct width or height ratio in code logic processing.
2. The image I saved should maintain the original EXIF, because I have no changes about EXIF.

### Steps to Reproduce

# Code

``` c#
void Test()
{
	var srcPath=@"C:\Users\Administrator\Desktop\test\1.jpeg";
	var targetPath=@"C:\Users\Administrator\Desktop\test\2.jpeg";
	
	using (var image = new ImageMagick.MagickImage(srcPath))
	{
		image.GetExifProfile().GetValue(ImageMagick.ExifTag.Orientation).Dump();
		image.AutoOrient();
		image.GetExifProfile().GetValue(ImageMagick.ExifTag.Orientation).Dump();
		image.Write(targetPath);
	}


	using (var image = new ImageMagick.MagickImage(targetPath))
	{
		image.GetExifProfile().GetValue(ImageMagick.ExifTag.Orientation).Dump();
	}
}
```
![image](https://github.com/dlemstra/Magick.NET/assets/9961428/97c8fa00-b720-45a3-8fd2-4f1dd1a60c22)

# Test File

[1.zip](https://github.com/dlemstra/Magick.NET/files/15398691/1.zip)

**Comment by dlemstra** [comment]
This is what is stated in the xml documentation: ` Adjusts an image so that its orientation is suitable for viewing.`

This means that the image is adjusted and because we are rotating the image we should also update the exif profile. If we would not do that would cause issues when someone loads your image and calls auto-orient. Or when an image viewer loads your image it would rotate the image again when it should not do that. And that is why we should update the value inside the exif profile.

p.s. Thanks for attaching the test file.

**Comment by xucongli1989** [comment]
Is there a way to reverse the `AutoOrient()` operation? For example:
``` c#
void Test()
{
	var srcPath = @"C:\Users\Administrator\Desktop\test\1.jpeg";
	var targetPath = @"C:\Users\Administrator\Desktop\test\2.jpeg";
	using (var image = new ImageMagick.MagickImage(srcPath))
	{
		var oldValue = image.Orientation;
		image.AutoOrient();
		//... something...
		image.Rotate(-90);
		image.Orientation = oldValue;
		image.Write(targetPath);
	}
}
```

**Comment by dlemstra** [comment]
I would advise you to create `.Clone()` of the image to preserve the state of the image.
