### ISSUE TITLE
Reading JPEG2000 images takes too long

### ISSUE THREAD

**Issue by Charltsing** [dlemstra/Magick.NET#1748]
### Magick.NET version

13.10.0

### Environment (Operating system, version and so on)

Windows10, net framework 4.7.2

### Description

I tried to read a Jpeg2000 image with a width of 6622 and a height of 4689, which took 6 seconds. Is this normal time?
How to optimize the time spent reading JPEG2000

![222](https://github.com/user-attachments/assets/c77b41a7-8c13-4899-8c40-b0f3a5c6e2f9)

[JPXDecode.zip](https://github.com/user-attachments/files/17687069/JPXDecode.zip)

settings.SetDefines(new Jp2ReadDefines
{
    QualityLayers = 100,
});

**Comment by dlemstra** [comment]
This is slow because of two reasons. I takes quite some time to decode the jp2 image and then also some time to copy this decoded data to our image data. The latter could be improved so I just pushed a patch to make the part that copies the pixels twice as fast. The other part is out of our control. This change will not become available in the next release because I was already preparing this and don't want to include this change at the last minute. So it might take a while before you will get this performance improvement.
