### ISSUE TITLE
Could not load file or assembly 'Magick.NET-Q8-x64' or one of its dependencies. An attempt was made to load a program with an incorrect format.

### ISSUE THREAD

**Issue by SingaraveluR** [dlemstra/Magick.NET#207]
Hello Everyone,

I am using Magick.NET-Q8-x64 in my project and I have created the project using VS 2017 when I build the project I'm getting the above mentioned error.

"Could not load file or assembly 'Magick.NET-Q8-x64' or one of its dependencies. An attempt was made to load a program with an incorrect format."

But in VS 2015 its working without any issues. Any help is appreciated.

Thanks in advance!

**Comment by dlemstra** [comment]
You should search for `An attempt was made to load a program with an incorrect format.` This is a generic error message and it would be nice if you could first search for that error message yourself. If you figure out what your issue was then please reply to this issue and close it. If you cannot find it yourself I will give you an explanation.

**Comment by dlemstra** [comment]
@SingaraveluR Could you add an explanation why you close this issue?
