### ISSUE TITLE
Creating MagicImage from MemoryStream fails

### ISSUE THREAD

**Issue by laphir** [dlemstra/Magick.NET#245]
Thank you for making a great library.

I found a problem that MagickImage cannot be created from a MemoryStream. Following code throws an exception `System.ArgumentException: Value cannot be empty.`
Magick.NET 7.0.* was fine. Any version later than this version throws an exception with the next code.
```
using (var s = File.OpenRead("img_1005.tif"))
using (var m = new MemoryStream())
{
    s.CopyTo(m);

    using (var i = new MagickImage(m))
    {
        Console.WriteLine("width={0}", i.Width);
    }
}
```

Your example code is creating a memory stream from byte[]. I tried next code, and it worked fine.
```
var b = File.ReadAllBytes("img_1005.tif");
using (var m = new MemoryStream(b))
{
    using (var i = new MagickImage(m))
    {
        Console.WriteLine("width={0}", i.Width);
    }
}
```

I'm not sure what's the difference between two MemoryStream objects. But it would be great if you can support both forms.

**Comment by dlemstra** [comment]
The reason that your second example works is because the position of `m` is zero. In your first example you are calling `CopyTo` and this will set the position of `m` at the end of the stream. Resetting it back to zero before you call the constructor should resolve the issue. This uses to work in older versions of Magick.NET but as you have noticed that bug has been fixed.

p.s. Why are you not passing in `s` to the constructor of `MagickImage`?

**Comment by laphir** [comment]
Wow, that was it. Thank you. I think we can close this thread.

p.s. Actual code is not using FileStream. It's a stream from an archive (like zip or rar). Some decoder supports only 1 decoding stream from archive, so I have to close input stream as soon as possible.
