### ISSUE TITLE
Tiled checkerboard behind image with transparency

### ISSUE THREAD

**Issue by simonmurdock** [dlemstra/Magick.NET#3]
I understand IM has this built in via some pattern parameter, but I do not know how to pass this in via Magick.NET.

Or even a way to specify my own checkerboard pattern as a jpg and tile it?

Could you possibly assist? :)

**Comment by dlemstra** [comment]
Do you know the command line variant of what you are trying to achieve? Do you want to draw an image over a tiled checkerboard background like Photoshop does?

**Comment by simonmurdock** [comment]
I tried some command line variants but had trouble getting those to work how I wanted.

But yes, I want to replicate the photoshop effect where the checkerboard is shown below the transparent areas of the image provided. in this case a .png file. But using my own image for the checkerboard, a 16x16 png file.

Thank you

**Comment by dlemstra** [comment]
You could also use the MagickImage.ColorAlpha method for and use a color instead of a pattern. But I think you would want to use the Tile method. Your first action has to be to extend the image to as size that it won't show 'half' of your pattern. A 30x20 image would become 32x32 in your case (16x16 pattern). And then you can use the following method `logo.Tile(pattern, CompositeOperator.??)` I am not sure which operator you would need, prob SrcOver or DstOver.

**Comment by simonmurdock** [comment]
I think i was using DstOver in my previous exmaples.

I will give that a go, thanks

**Comment by simonmurdock** [comment]
Just For my information - is there a methodology to how the API is laid out for Magick.net? Because I can often find a raw imageMagick commandline for what I want to do, but find it very difficult to convert that to a Magick.Net way.

**Comment by dlemstra** [comment]
Most command line options are methods/properties on the MagickImage class. There are some examples available here: https://magick.codeplex.com/documentation but I agree with you that this project needs more and better documentation. I don't have/make enough time for that.

**Comment by simonmurdock** [comment]
ah okay, I might have a go some day
thank you for your help! working nicely.
