### ISSUE TITLE
"Contains code not compatible with .net core"

### ISSUE THREAD

**Issue by Tylertron1998** [dlemstra/Magick.NET#314]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### Question

Hey there! Just got a little warning from Rider, my IDE, saying that the constructor for the MagickImage class is not compatible with .net core - https://imgur.com/a/c1CGW1k.

Any idea with this - is it true?

**Comment by Tylertron1998** [comment]
Ah, interesting. Time to report to the Rider developers. Thanks!

Out of interest, do you mean the Bitmap class under System.Drawing? As I believe there is a nuget package for that, in core.

**Comment by dlemstra** [comment]
I do mean the Bitmap class under System.Drawing but I have some compiler definition to make sure that this is not part of the `netstandard` build.

**Comment by dlemstra** [comment]
I have no idea why you would get that warning...

**Comment by dlemstra** [comment]
Could you copy paste the whole error message here?

**Comment by Tylertron1998** [comment]
That's everything there - that error, and obviously my IDE's warning I screenshotted above. Unless there is something I'm missing? Sorry for the long reply again.

**Comment by dlemstra** [comment]
I was unable to read the text on my phone because the browser resized the image. Next time it will be easier for me if you copy paste the error message. I am now on my desktop so I can read the text in the image. 

I can now finally see that you are trying to use the OpenMP version of the package. That version of the library is not compatible with .NET core at the moment. I might add an OpenMP Linux/MacOS build in the future and then add .net core support for this version of the library. But I have no idea if or when this will happen.

**Comment by Tylertron1998** [comment]
Hey @dlemstra - just wondering, any update on OpenMP support for .net core on linux?

**Comment by dlemstra** [comment]
No update at this point in time, still hoping I will get some help.

**Comment by Tylertron1998** [comment]
I'd love to help, however I'd imagine this would require working with the C++ bridge code, right?

**Comment by dlemstra** [comment]
Closing this because version the latest releases have support for OpenMP on Linux.
