### ISSUE TITLE
Support Raspberry Pi or Linux-arm ？

### ISSUE THREAD

**Issue by chaoweiyi** [dlemstra/Magick.NET#380]
Can it be supported in the next version?

**Comment by dlemstra** [comment]
I don't know what needs to be done to make this possible. I can take a look at it but I don't think that support can be added before the next release.

**Comment by chaoweiyi** [comment]
Thanks a lot !

**Comment by chaoweiyi** [comment]
I appreciate your help.

**Comment by PatrykPorabik** [comment]
Hello,
Any news when arm64 will be supported? We've tried to install our app with your library on Raspberry, Ubuntu 18.04 with arm64 processor, but we failed. Do you know the estimates when it will be possible?

**Comment by dlemstra** [comment]
I cannot give you an estimate because this all depends on when AzureDevOps will have arm64 support. And at this moment it has no support for that.

**Comment by nixcamic** [comment]
AFAIK AzureDevOps now has support for arm64. arm/arm64 would also be super useful for Xamarin.Android projects.

**Comment by dlemstra** [comment]
The build has moved from AzureDevOps to GitHub. Not sure if they support an ARM build.

**Comment by nixcamic** [comment]
AFAIK they claim to support ARM. If I knew more about the GitHub build process I would test it myself.

**Comment by he852100** [comment]
I seem to need it.

**Comment by derBobo** [comment]
are there any news for an arm/arm64 build ?

**Comment by rosenbjerg** [comment]
I would also like arm32 and arm64 support

**Comment by dlemstra** [comment]
Waiting for ARM support in GitHub actions for the open source developers.

**Comment by rosenbjerg** [comment]
You can build ARM images on the GitHub build agents using Docker buildx/Docker experimental features.
See crazy-max/ghaction-docker-buildx
Docker then uses qemu for arm32 and arm64

**Comment by marshalhayes** [comment]
I stumbled upon this issue while trying to get the library working on my Raspberry Pi 4b. Everything ran extremely smoothly on my MacBook pro, so I was surprised it didn't on Linux. 

My Raspberry Pi 4b is running a 64-bit version of Debian, but I think I'm having similar issues to everyone here: The library dll is passed along in my deployment process, but performing any operations with it throws a `System.DllNotFoundException` exception and sometimes a `System.BadImageFormatException`. 

I assume this is related to support for arm64 processors?

```
marshal@rpi1:~$ uname -a
Linux rpi1 5.7.0-2-arm64 #1 SMP Debian 5.7.10-1 (2020-07-26) aarch64 GNU/Linu
```

Are there any steps I can take to get this working, or do I need to wait until GitHub actions supports ARM processors?

**Comment by dlemstra** [comment]
For this to work I will need to do an arm64 build of the Magick.Native library. The complete build has now moved to GitHub and we need to wait till they will provide support for the open source projects.

**Comment by Y56380X** [comment]
I tried to cross-compile Magick.Native for ARM64 on a Ubuntu x64 machine and copy the .so file manually. It kind of works for my purposes but some dependencies failed to build properly. (Forked for build script adjustments to [Y56380X/Magick.Native](https://github.com/Y56380X/Magick.Native))

Failing dependencies:

- openjpeg
- glib
- lqr
- pango
- croco
- librsvg

**Comment by Seabizkit** [comment]
Please add this..... busy setting up a project now and converting to Arm, and was kind stomped back when this is not working.

is there an ETA? Please give this some LOVE

**Comment by dlemstra** [comment]
You will need to ask GitHub for the ETA. Read my response:

> For this to work I will need to do an arm64 build of the Magick.Native library. The complete build has now moved to GitHub and we need to wait till they will provide support for the open source projects.

**Comment by EraYaN** [comment]
It is feasible (and probably faster) approach to building ARM anything to run a cross compile, like for example something like this:

https://github.com/jellyfin/jellyfin-skiasharp-native/tree/master/Jellyfin.SkiaSharp.NativeAssets.LinuxArm

Don't think you need to run specifically on ARM to compile for it.

**Comment by dlemstra** [comment]
If you want to build Magick.NET with ARM support on your local machine you will need to clone this repository: https://github.com/dlemstra/Magick.Native. There are no instruction on how to build it with ARM support but you could probably follow the build steps on Linux.

**Comment by barrct** [comment]
Alright, so following the suggestion from @dlemstra I have some notes.

1. The process does not work with the cloned repo as of 2021/10/21. There are issues in the install.dependencies.sh script, please see the issue https://github.com/dlemstra/Magick.Native/issues/12
Fixing the issues is quite simple. You just need to remove the python-pip package, but you will also need to add a couple of other packages that my install did not seem to have available when needed in the later steps **cmake meson libxml2-dev libxslt-dev**. Additionally, the gcc-7 and g++-7 need converted to gcc and g++ as apt install was reporting them as depreciated.
This is the final edited script that was able to allow for a clean compile on an INTEL processor (before I tried to move to the ARM)

This is my install.dependencies.sh now what give me a clean compile on Ubuntu x86.

------------------------------------------------------------------------------------------------------
#!/bin/bash
set -e

apt-get update -y

**#apt-get install -y autoconf autopoint gettext git gperf libtool nasm pkg-config python python-pip python3-pip ragel software-properties-common texinfo**
apt-get install -y autoconf autopoint gettext git gperf libtool nasm pkg-config python python3-pip ragel software-properties-common texinfo cmake meson libxml2-dev libxslt-dev

**#add-apt-repository ppa:ubuntu-toolchain-r/test -y**
apt-get update -y
**#apt-get install gcc-7 g++-7 -y**
apt-get install gcc g++ -y
**#update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7**
**#update-alternatives --config gcc**

pip3 install cmake
pip3 install meson==0.55.3
pip3 install ninja==1.10.0.post2

------------------------------------------------------------------------------------------------------

2. This would be the commands to run in order for the clean compile in an x86 chip.
sudo apt install git
sudo git clone https://github.com/dlemstra/Magick.Native.git
**-= Fix the install.dependencies.sh script =-**
vi Magick.Native/build/linux/install.dependencies.sh
**-= Fix the install.dependencies.sh script =-**
cd Magick.Native/build/linux
sudo ./install.dependencies.sh linux
cd ../../src/ImageMagick/
sudo ./checkout.sh linux ../../../artifacts
cd libraries/
sudo ../../../build/linux/build.libraries.sh ../../../build/libraries
cd ../../../src/ImageMagick/libraries/
sudo ../../../build/linux/build.ImageMagick.sh
cd ../../Magick.Native/
sudo ../../build/linux/build.Native.sh

You now have compiled objects.

ls Q16
CMakeCache.txt  CMakeFiles  cmake_install.cmake  **libMagick.Native-Q16-x64.dll.so**  Makefile

file Q16/libMagick.Native-Q16-x64.dll.so
Q16/libMagick.Native-Q16-x64.dll.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=8153f0576df8bfc6c77602db11b1db51aecf41a7, with debug_info, not stripped

That was on Ubuntu.
uname -a
Linux <redacted> 5.13.0-20-generic #20-Ubuntu SMP Fri Oct 15 14:21:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Debian doesn't seem to be very happy.
uname -a
Linux barr-debian 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
./install.dependencies.sh
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Ign:4 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Err:5 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu jammy Release
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Now, I can't say that they are 100% stable as right now I'm focusing on getting a clean build process to replicate on the Raspbery Pi.

3. So, you ask.... "If that worked on the x86, how did it go on the Pi?"
Eh, not great.

When compiling the libraries, there's an error.

libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I. -I../include -Iinclude -I../src -I/usr/local/include -I. -I../include -Iinclude -I../src -O3 -fPIC -MT src/arm/sysv.lo -MD -MP -MF src/arm/.deps/sysv.Tpo -c ../src/arm/sysv.S -o src/arm/sysv.o
../src/arm/sysv.S: Assembler messages:
../src/arm/sysv.S:399: conditional infixes are deprecated in unified syntax
../src/arm/sysv.S:410: Error: undefined symbol FFI_TYPE_STRUCT_VFP_FLOAT used as an immediate value
../src/arm/sysv.S:411: Error: undefined symbol FFI_TYPE_STRUCT_VFP_DOUBLE used as an immediate value
../src/arm/sysv.S:450: Error: undefined symbol FFI_TYPE_STRUCT_VFP_FLOAT used as an immediate value
../src/arm/sysv.S:453: Error: undefined symbol FFI_TYPE_STRUCT_VFP_DOUBLE used as an immediate value
make[2]: *** [Makefile:1401: src/arm/sysv.lo] Error 1
make[2]: Leaving directory '/root/Magick.Native/src/ImageMagick/libraries/ffi/armv7l-unknown-linux-gnueabihf'
make[1]: *** [Makefile:1659: install-recursive] Error 1
make[1]: Leaving directory '/root/Magick.Native/src/ImageMagick/libraries/ffi/armv7l-unknown-linux-gnueabihf'
make: *** [Makefile:3237: install] Error 2

Then compiling ImageMagick

 /usr/bin/mkdir -p '/usr/local/share/ImageMagick-7'
 /usr/bin/install -c -m 644 config/english.xml config/francais.xml config/locale.xml '/usr/local/share/ImageMagick-7'
 /usr/bin/mkdir -p '/usr/local/lib/ImageMagick-7.1.0/config-Q16HDRI'
 /usr/bin/install -c -m 644 config/configure.xml '/usr/local/lib/ImageMagick-7.1.0/config-Q16HDRI'
 /usr/bin/mkdir -p '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 MagickCore/ImageMagick.pc MagickCore/ImageMagick-7.Q16HDRI.pc MagickCore/MagickCore.pc MagickCore/MagickCore-7.Q16HDRI.pc MagickW                                                                                and/MagickWand.pc MagickWand/MagickWand-7.Q16HDRI.pc '/usr/local/lib/pkgconfig'
make[2]: Leaving directory '/root/Magick.Native/src/ImageMagick/libraries/ImageMagick'
make[1]: Leaving directory '/root/Magick.Native/src/ImageMagick/libraries/ImageMagick'
mkdir: cannot create directory ‘/usr/local/include/ImageMagick-7/coders’: File exists

And then Magick.Native.

[ 95%] Building C object CMakeFiles/Magick.Native-Q8-x64.dll.dir/Types/TypeMetric.c.o
[ 97%] Building CXX object CMakeFiles/Magick.Native-Q8-x64.dll.dir/foo.cxx.o
make[2]: *** No rule to make target '/usr/local/lib//liblqr-1.a', needed by 'libMagick.Native-Q8-x64.dll.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/Magick.Native-Q8-x64.dll.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

I'm guessing the failing libraries can be skipped, but if anyone has thoughts on the main ImageMagick and Magick.Native, I'd love to hear them so that we can maybe get a ARM object for Apples and Pis.
Since she compiles on x86/Ubuntu, I'm not sure if figureing out how to cross-compile it to ARM64 is the answer or if the best option is to start to see why Raspi doesn't like it, possibly becuase of it's Debian backgroud since Debian can't compile the x86 version.
I will start to work though the library errors and see if clearing that up helps ImageMagick compile.
If anyone has cross-compiled before since I never have, that might be the solution as it seems to work on the X86 OS.

**Comment by c-harris** [comment]
@barrct I am just working through the same process, did you have any luck replicating?

**Comment by kurattila** [comment]
@dlemstra @barrct Any news on Linux ARM builds?

**Comment by dlemstra** [comment]
Support for arm64 on Windows was recently added because it was easy to do a cross compilation with VisualStudio. Adding support for Linux ARM builds will probably not be added anytime soon.

**Comment by mikart143** [comment]
As .Net Maui became new standard for making apps in .net world, any chances to make this happen to run on arm ?

**Comment by dlemstra** [comment]
Good news support for Linux ARM64 was added. This will become available in the next release. This does not include support for jpeg-xl but support for this might be added in a future release.

**Comment by dlemstra** [comment]
Support for jpeg-xl in the Linux ARM64 build was added in the latest release.

**Comment by gswdn** [comment]
Nice, that ARM64 seems to be fully supported now. Good work!

As regular raspberry raspian is (still) 32 bit, any estimate, how far it is from ARM64 to ARM and if that is something going to be implemented as well?

**Comment by dlemstra** [comment]
I am not going to add 32 bit support for ARM.

**Comment by gswdn** [comment]
@dlemstra : Thank you for clarifying and letting us know. That really helps to plan my project. Hope, that 64bit raspian will become common soon.
