### ISSUE TITLE
SigmoidalContrast *sometimes* causes artifacts to appear

### ISSUE THREAD

**Issue by pranavmehta** [dlemstra/Magick.NET#390]
Using Magick.NET-Q8-AnyCPU v 7.11.0

Am converting an image to HCL colorspace, and performing a SigmoidalContrast on the chroma channel. The code looks something like below:

```
ColorSpace OrigColorSpace = Image.ColorSpace;

Image.ColorSpace = ColorSpace.HCL;
using (MagickImageCollection images = new MagickImageCollection(Image.Separate()))
{
   Percentage PCT = new Percentage(0);
   images[1].SigmoidalContrast(true, 2.1f, PCT);
   MagickImage EnhancedImage = (MagickImage) images.Combine(ColorSpace.HCL);
   EnhancedImage.ColorSpace = OrigColorSpace;
   return EnhancedImage.ToBitmap();
}
```
The above code works correctly 99% of the time without any artifacts, but in rare cases causing artifacts to appear. I've attached the source file and before/after as example.

**UPDATE:** On further testing it seems like its not the SigmoidalContrast that is the problem. Its the process of splitting and combining that is causing the issue. You can comment out the SigmoidalContrast line in the above code and still reproduce the issue.

![image](https://user-images.githubusercontent.com/7125283/53020706-847f4380-347d-11e9-875b-82cfc4bbbf49.png)

Original source image to reproduce the issue:
![kechup](https://user-images.githubusercontent.com/7125283/53020747-9eb92180-347d-11e9-8266-0e75815214d6.jpg)

**Comment by dlemstra** [comment]
Sorry for the delayed response but I have been away for a long time. Only had a phone and not a debugger so I could check this better. And I think I have figured out why this is happening. 

The problem seems to be the color space conversion. You are using the Q8 build and that does not seem to be precise enough for conversion from sRGB to HCL and then back to sRGB. Switching to the Q16 build seems to resolve the issue because you have a range of `0-65535` then instead of `0-255`.
