### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'kernel32.dll': 

### ISSUE THREAD

**Issue by senlin2684** [dlemstra/Magick.NET#490]
I use Magick.NET-Q16-AnyCPU.7.14.0.3/lib/net20/Magick.NET-Q16-AnyCPU.dll to unity3d Plugins ,publish to ios(ipad), when excute throw exception  
"DllNotFoundException: Unable to load DLL 'kernel32.dll': The specified module could not be found.
  at ImageMagick.MagickNET+NativeWindowsMethods.SetDllDirectory (System.String lpPathName) [0x00000] in <filename unknown>:0 ", 
when i use api second   throw exception "Unloading 1 Unused Serialized files (Serialized files now loaded: 0)
DllNotFoundException: Unable to load DLL 'Magick.NET-Q16-x64.Native.dll': The specified module could not be found."

magick.net can used on ios?

**Comment by dlemstra** [comment]
The `MagickNET.SetNativeLibraryDirectory` method only works on Windows at the moment but it looks like it can also be called on other platforms. Will need to figure out how to fix this.

**Comment by dlemstra** [comment]
I just published `7.14.1.0` and that does not yet include a fix for this. I thought I had to go through a lot of files to fix this but it turned out to be an easy fix. In the next release this method will silently do nothing on non-windows platforms. And I will need to figure out how to get this method working on non-windows platforms.
