### ISSUE TITLE
MagickImage gives me thumbnail size when passing bytes[] of RAW format

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#538]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I just encountered a very weird problem. 
Sample files: 
- DNG: https://github.com/d2phap/ImageGlass-Sample-Images/tree/master/Samples/DNG
- CR2: https://github.com/d2phap/ImageGlass-Sample-Images/tree/master/Samples/CR2 

If I pass `bytes[]` to the `new MagickImage()`, I get the thumbnail size!
The `settings` variable is just `new MagickReadSettings()`

```csharp
var allBytes = File.ReadAllBytes(filename);
using (var imgM = new MagickImage(allBytes, settings))
{
  // imgM.Width = 320 px !! ❌
}
```

Using directly filename has no problem
```csharp
using (var imgM = new MagickImage(filename, settings))
{
  // imgM.Width = 5216px ✔
}
```

### Steps to Reproduce
The below test used file `L1004235.dng` in the link above

![image](https://user-images.githubusercontent.com/3154213/69057426-d1179f80-0a4c-11ea-8b9a-d0dbd3916d59.png)

![image](https://user-images.githubusercontent.com/3154213/69057433-d543bd00-0a4c-11ea-9ff8-3bd0e971d5d4.png)

### System Configuration
- Magick.NET version: 7.14.5.0
- Environment (Operating system, version and so on): Windows 10 insider b19025

Thanks a lot!

**Comment by dlemstra** [comment]
This is happening because the `DNG` coder cannot detect the `DNG` or `CR2` format from the header of the file. But it turns out that this is possible for the `CR2` format so I just pushed a patch to add support for this to ImageMagick. This will become available in the next release. But I was unable to find a header for the `DNG` format and because this starts with the same bytes as a `TIFF` file the image is being detected as a tiff image instead.

**Comment by dlemstra** [comment]
Support for detecting `CR2` has been added in the latest release (` 7.15.0.0`)

**Comment by d2phap** [comment]
thanks
