### ISSUE TITLE
ImageCollection GIF compression

### ISSUE THREAD

**Issue by NotOfficer** [dlemstra/Magick.NET#555]
Hi,
is there a way to render an ImageCollection to a GIF without losing quality (or at least almost no quality loss)?
Ive been trying to change some settings but it keeps looking pixelated.

**Comment by dlemstra** [comment]
Can you please share an example image and code that demonstrates this?

**Comment by NotOfficer** [comment]
So im generating like that one (5 in total): [Image 1/5](https://cdn.discordapp.com/attachments/659615856497786882/660154635579031572/BR_News_1.jpg)
and add them to an imageCollection:
```cs
var imageCollection = new MagickImageCollection();
foreach (var x in y)
{
    var image = new MagickImage(x.ImageBytes); //jpeg format
    //editing the image...
    image.AnimationDelay = 500;
    imageCollection.Add(image);
}
var gifBytes = imageCollection.ToByteArray(MagickFormat.Gif);
```
which results in that: [GIF Image](https://cdn.discordapp.com/attachments/659615856497786882/660154643162202155/BR_News.gif)

**Comment by NotOfficer** [comment]
Another thing i noticed in the meantime is that the `TextDirection` property from `MagickReadSettings` (`RightToLeft`) didnt work for caption and label images. I tried multiple fonts with arabic and non-arabic text and it was still `LeftToRight` directed.

**Comment by dlemstra** [comment]
The gif format only supports 256 different colors per frame. There are some tricks to work around this (https://webmasters.stackexchange.com/questions/304/can-i-have-an-animated-gif-with-more-than-256-colours-per-frame) but since you have an animation I suspect this won't work for you.

p.s Could you open a new issue for the TextDirection problem you appear to have? And please include a sample of what you would expect since I don't know what arabic text should look like.
