### ISSUE TITLE
ImageMagick.MagickCoderErrorException : 'IDAT: CRC error `' @ error/png.c/MagickPNGErrorHandler/1715'

### ISSUE THREAD

**Issue by 0xRaf** [dlemstra/Magick.NET#562]
### Prerequisites / Description

Hi !

Everytime I run the following code on the specified PNG image I get "ImageMagick.MagickCoderErrorException : 'IDAT: CRC error `' @ error/png.c/MagickPNGErrorHandler/1715'".

I searched for this issue in this repository, on GitHub, on StackOverflow and everywhere on Google but I can't find anything useful regarding "ImageMagick.MagickCoderErrorException", "IDAT: CRC error" nor "error/png.c/MagickPNGErrorHandler/1715", so I post it here.

### Steps to Reproduce

```CS
using ImageMagick;
using System.Net;

namespace MagickCRCError
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            byte[] data;
            using (WebClient client = new WebClient())
            {
                data = client.DownloadData("https://www.muenzeoesterreich.at/var/em_plain_site/storage/images/_aliases/product_full/media/bilder/produktbilder/2.sammeln/2.2.5_euro/5e_2018_osterhase_set/3970854-2-ger-DE/5e_2018_osterhase_set.png");
            }

            MagickImage image = new MagickImage(data);
            image.BackgroundColor = MagickColors.White;
        }
    }
}
```

### System Configuration

- Magick.Net version : 7.15.0
- .Net version : Core 3.0
- OS version : Windows 10 1909 x64 (18363.592)

It's probably an issue from the PNG itself (CRC Error) but I can open it in any web browser or image viewer so it's a bit weird to me.
Feel free to close this issue if I have missed something.

Anyway, thanks for developing Magick.Net !

**Comment by dlemstra** [comment]
The ImageMagick library that is being used by Magick.NET is very strict about the PNG file being valid. And it appears that your file is not valid. There is an option to disable CRC checking and I should add that to the `PngReadDefines` but I tried that on the command line and it then still fails to read the file. Other programs can read the image because they are less strict about the contents of the file and probably ignore a lot of information that is still being read by ImageMagick.

**Comment by 0xRaf** [comment]
Thanks for you answer !
I just added a check for `ImageMagick.MagickCoderErrorException` in my code and everything goes fine.

**Comment by LucasStark95** [comment]
How to disable to option CRC in code C#?

**Comment by 0xRaf** [comment]
I just did
```cs
try
{
	//Magick stuff here
}
catch (MagickCoderErrorException e)
{
	//Stuff didn't work because a CRC error occured
}
```

**Comment by LucasStark95** [comment]
Thank's!!!

Em qui., 12 de mar. de 2020 às 16:52, Raf <notifications@github.com>
escreveu:

**Comment by Wabbbit** [comment]
@dlemstra Apolgies for the necro-thread but I have the same issue.

As per @LucasStark95 comment above, what is the correct method of disabling the CRC check to avoid the "MagickPNGErrorHandler/1715" error? I can't work it out from scanning the source easily.

Simply wrapping in an exception handler as per above only stops errors bubbling up.

I have tried:

```
  var defs = new PngReadDefines()
        {
          IgnoreCrc = true,
        };
```
and applying this to all my images like:

```
image1.Settings.SetDefines(defs);
 image2.Settings.SetDefines(defs);
 diffImage.Settings.SetDefines(defs);

```
But this line `  diffImage.Write(diffPath);`

still fails with the exception `{"WriteBlob Failed `diff.png' @ error/png.c/MagickPNGErrorHandler/1715"}`

This only happens when I edit one of the PNG files manually rather than them being PNG ouput from ImageMagick.

**Comment by dlemstra** [comment]
Could you create a new issue @Wabbbit and explain in more detail (with a test image) the issue that you are experiencing?
