### ISSUE TITLE
Support JXR (JPEG extended range) format

### ISSUE THREAD

**Issue by moh-hassan** [dlemstra/Magick.NET#58]
I tried to read information about .jxr images , then do some processing, but i can't find that type in MagickFormat.xxx

 My code:

        try
        {
            //MagickFormatInfo first = MagickFormatInfo.Create(MagickFormat.Jpeg); //just as a try , bez jxr is not defined
            MagickFormatInfo second = MagickNET.GetFormatInformation(@"images\myimage.jxr");
            Console.WriteLine(second.Format);
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);            
        }

The exception is:

         Object reference not set to an instance of an object.

I know that imagemagick support jxr format using the library jxrlib( https://www.imagemagick.org/script/formats.php)

Thanks

**Comment by dlemstra** [comment]
The format is supported but you will need to do some 'magick' to make it work. Reading JXR files will only work when you copy the file `JXRDecApp.exe` to your bin directory and read from a file on disk that has a `.jxr` extension. Reading from a byte array is not supported. It would be nice if the code of the jxrlib project (http://jxrlib.codeplex.com) could be part of ImageMagick. Maybe I should create an issue for this in the ImageMagick project. You will need to compile `JXRDecApp.exe` yourself because there are no binaries available.

**Comment by moh-hassan** [comment]
Thanks for help and support.
I really used JXRDecApp.exe and JXREncApp.exe (after compiling the source code in vs 2015) from within ImageMagick to convert to/from jxr files.
 
I hope that MagickFormat.xxx have jxr entry and reading from a JXR  byte array can be  supported.

**Comment by dlemstra** [comment]
You could ask for support for that here: https://github.com/ImageMagick/ImageMagick/issues

**Comment by moh-hassan** [comment]
ImageMagick project handle jxr as a file using the ready made Executable files from codeplex jxrlib project. I think for handling it as a byte array we should contact codeplex project which is not active since 2013. 
Thanks
