### ISSUE TITLE
ImageMagick.NET v7.15.x is 4x slower than v7.14.x

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#594]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
ImageMagick.NET v7.15.x is 4x slower than v7.14.x.
This happened since the v7.15.0, I believe it's because of the refactoring.

### Steps to Reproduce
After investigating for a while, I realized there are 2 things:

#### 1. Using MagickImageCollection to load multiple pages of TIFF file take 4x slower
```csharp
using (var imgColl = new MagickImageCollection(filename, settings))
{
    var bitmap = imgColl.ToBitmap();
}
```

Sample file: [050-5001-B_Twiggy_Analog_New.zip](https://github.com/dlemstra/Magick.NET/files/4362518/050-5001-B_Twiggy_Analog_New.zip)

`v7.14.x` | `v7.15.x`
--- | ---
5 seconds | 20 seconds

#### 2. Getting color profile of a JPG file also takes 2-3 times longer
```csharp
using (var imgM = new MagickImage(filename, settings))
{
    var colorProfile = imgM.GetColorProfile();
}
```
Sample file: [IMG_5759.JPG](https://user-images.githubusercontent.com/3154213/77220998-9485bd00-6b80-11ea-87da-468a2449a785.jpg)

### System Configuration

- Magick.NET version: 7.15.4.0
- Environment (Operating system, version and so on): Windows 10 build 19582
- Additional information: Core i7 with NVIDIA GeForce 940MX

**Comment by dlemstra** [comment]
The first issues is probably caused because you switched to a `MagickImageCollection`. Your test image has a single frame and I just added an optimization that for a single image it will use the `ToBitmap` method of the image itself. That is faster because it will not first convert the image into a `tiff` file. In your use case you might want to switch to calling `ToBitmap` for each individual image in your collection.

I am unable to reproduce your second issue with ImageMagick `7.14.0`. I get the same time with both versions.

**Comment by d2phap** [comment]
Thanks @dlemstra

It's because i want to get the number of pages in TIF/GIF. Or is there better way to do it without using the collection?

For the second issue, i will build a sample project and send you.

**Comment by d2phap** [comment]
@dlemstra 
The poor performance happens on `imgM.AddProfile(ColorProfile.SRGB);` function.
Please see the screenshots below.

### Source code: [App1.zip](https://github.com/dlemstra/Magick.NET/files/4369385/App1.zip)

```csharp
private void button1_Click(object sender, EventArgs e)
{
    var of = new OpenFileDialog();

    if (of.ShowDialog() == DialogResult.OK)
    {
        var watch = new System.Diagnostics.Stopwatch();
        watch.Start();

        //Load image
        pictureBox1.Image = LoadImage(of.FileName);

        watch.Stop();
        button1.Text = $"{watch.ElapsedMilliseconds} ms";
    }
}


private Bitmap LoadImage(string filename)
{
    Bitmap bitmap = null;

    using (var imgM = new MagickImage(filename, new MagickReadSettings()))
    {
        imgM.Quality = 100;

        var imgColorProfile = imgM.GetColorProfile();
        if (imgColorProfile != null)
        {
            imgM.ColorSpace = imgColorProfile.ColorSpace;

            // correct the image color space
            imgM.AddProfile(ColorProfile.SRGB);
            imgM.ColorSpace = ColorProfile.SRGB.ColorSpace;
        }

        bitmap = imgM.ToBitmap();
    }

    return bitmap;
}
```

### Performance
#### v7.15.5.0 🐌
![image](https://user-images.githubusercontent.com/3154213/77318318-d876ee80-6d47-11ea-8e8d-ddee292b2ba2.png)

#### v7.14.5.0 💨
![image](https://user-images.githubusercontent.com/3154213/77318332-ddd43900-6d47-11ea-9d67-e4eabefc8e4d.png)

**Comment by dlemstra** [comment]
Thanks for your example. I am now also able to reproduce your issues. I forgot that I need to do a rebuild after changing the NuGet package version. The reason that this is happening is due to a change in the `AddProfile` method. The internal ImageMagick now uses doubles instead of shorts to do the color transformtion. We could add an option to allow the old behaviour. But it will take some time to make these changes.
