### ISSUE TITLE
Blazor WebAssembly: DllNotFoundException: Magick.Native-Q16-x86.dll assembly is thrown when using using Magick.NET-Q16-AnyCPU

### ISSUE THREAD

**Issue by velikovmartin** [dlemstra/Magick.NET#716]
### **Prerequisites**

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using the **Magick.NET-Q16-AnyCPU** NuGet package in a **Blazor WebAssembly** a _System.DllNotFoundException: Magick.Native-Q16-x86.dll assembly_ is thrown. It seems that this NuGet depends on the Magick.Native-Q16-x86, but it cannot be accessed by the browser.

### Steps to Reproduce
Use the following code snippet: 

```
string pngImageBase64String = "...";
byte[] pngImageData = Convert.FromBase64String(pngImageBase64String);
byte[] jpegImageData;
using (MagickImage magickImage = new MagickImage())
{
	magickImage.Format = MagickFormat.Jpeg;
	magickImage.Alpha(AlphaOption.Remove);
	jpegImageData = magickImage.ToByteArray();
}
```

or check the **attached project**.

### System Configuration

- Magick.NET version: 7.21.1
- Environment (Operating system, version and so on): Windows 10 Pro, version: 10.0.17134 Build 17134

[BlazorApp_Magick.NET_Bug.zip](https://github.com/dlemstra/Magick.NET/files/5096330/BlazorApp_Magick.NET_Bug.zip)

**Comment by dlemstra** [comment]
You cannot use this library in Blazor because that does not support executing code in a native library. You might want to switch to something like ImageSharp (https://github.com/SixLabors/ImageSharp) and give that a try. And if you want to go fully WASM/Java/Typescript you could also give this library a try: https://github.com/dlemstra/Magick.WASM.

**Comment by itb-jsm** [comment]
Hi Dirk

We are a few years later, is there any view on supporting it natively, I read the following on the MS website:

> Package native dependencies in a NuGet package
> NuGet packages can contain native dependencies for use on WebAssembly. These libraries and their native functionality are then available to any Blazor WebAssembly app. The files for the native dependencies should be built for WebAssembly and packaged in the browser-wasm [architecture-specific folder](https://learn.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks#architecture-specific-folders). WebAssembly-specific dependencies aren't referenced automatically and must be referenced manually as NativeFileReferences. Package authors can choose to add the native references by including a .props file in the package with the references.
https://learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?view=aspnetcore-7.0

The reason I'm asking, I have many encrypted ImageMagickCollection files. And I'm now trying to build a Blazor WebAssembly tool as a new frontend GUI to consume those files. Due to security and privacy, I want to decrypt them in the browser.

**Comment by dlemstra** [comment]
Can you not use the magick-wasm library that I mentioned earlier instead then? And feel free to start a discussion in that repository if you are missing functionality.

**Comment by BenMcLean** [comment]
> Can you not use the magick-wasm library that I mentioned earlier instead then? And feel free to start a discussion in that repository if you are missing functionality.

How would someone include magick-wasm in a Blazor WebAssembly C# app?

**Comment by dlemstra** [comment]
I have not done this myself yet so I cannot give you some help or instructions on how to do that. Maybe you can borrow some ideas from this project: https://github.com/dlemstra/magick-wasm-docs? It uses Vue but it might help you?
