### ISSUE TITLE
Support Asynchronous Programming

### ISSUE THREAD

**Issue by bradlis7** [dlemstra/Magick.NET#765]
### Is your feature request related to a problem? Please describe
Reading from a file system or stream can be done asynchronously, which would improve application response.

### Describe the solution you'd like
I don't think you could do it in the constructor, but you'd have to do so in a static method.

```
public class MagickImage {
    public static MagickImage OpenAsync(...) {}

    public async Task WriteAsync(...) {}
}
```

### Describe alternatives you've considered
Perhaps wrapping certain calls in a Task block, but it's not making it truly asynchronous.

**Comment by dlemstra** [comment]
The reason that there is no asynchronous API is because the stream is read from the C code and that has no asynchronous support. 

An option to add an asynchronous API would be to read from the stream async and copy that to a byte array and pass it to the C library. And the same could be done when writing async. Let the C library create a byte array and write that to the output stream asynchronous. But not sure if that would be much of an improvement though.

**Comment by bradlis7** [comment]
Ah, I understand. I can do that in my code. Feel free to close this with the workaround unless you'd like to implement it in the library.

**Comment by dlemstra** [comment]
I don't mind adding async Read and Write methods.
