### ISSUE TITLE
limit memory

### ISSUE THREAD

**Issue by simonmurdock** [dlemstra/Magick.NET#8]
Hi, 
Is there a way to provide the same  "-limit memory 500" via Magick.NET? Currently it's using 4+ gigs converting a 200 page PDF.

Thanks

**Comment by dlemstra** [comment]
You could use the Memory property of ResourceLimits for this but I don't think it will help when you convert a 200 page PDF file. This is because that part is handled by Ghostscript (you need to license this if you use it commercial).

I think it would be better to do a page by page conversion. You can read a single page if you use the MagickReadSettings and set the FrameIndex or you can read the file like this: input.pdf[0] (reads the first page).

**Comment by simonmurdock** [comment]
ok cool ill try the page by page approach, if not i may have to call IM directly, as it seems to have a very different memory profile.

Does Magick.NET actually pull the data inside the CLR etc? or just forward calls?

**Comment by dlemstra** [comment]
Magick.NET will probably directly call the Ghostscript library. And maybe convert.exe will call the command line command for Ghostcript. That could explain the memory profile. You should see an other process 'eating' all your memory. Or you are using the 64-bit version of IM and convert.exe uses the 32-bit one.

I am not sure what you mean by your other question. I think you are asking of the unmanged code is copied to managed code. This is not happening, all the calls are 'forwarded' from managed to unmanged code.

**Comment by simonmurdock** [comment]
ok that sounds good I'll go and have a look. Id say we can close this for now. Thanks for your help
