### ISSUE TITLE
MagickFormat.Gray returns byte array where all bytes are zero (0)

### ISSUE THREAD

**Issue by duckheadsoftware** [dlemstra/Magick.NET#844]
### Description
When using magickImage.Format = MagickFormat.Gray; and then magickImage.ToByteArray(); all bytes in the returned array are zero.

The full process I'm performing is:

using var magickImage = new MagickImage(stream);
var size = new MagickGeometry(width, height) { IgnoreAspectRatio = true };
var settings = new QuantizeSettings { ColorSpace = ColorSpace.Gray, Colors = 256 };
magickImage.Resize(size);
magickImage.Quantize(settings);
magickImage.Format = MagickFormat.Gray;
var result = magickImage.ToByteArray();

This resizes the image (if I run toByteArray after that, I get an array of bytes as expected, i.e. they have values).
Then it converts the image to a maximum of 256 colors (quantize) (if I run toByteArray after that, I get an array of bytes as expected, i.e. they have values).
Then I change the format to gray (to reduce the pixels to 1 byte per pixel) - I run toByteArray after that, I get an array of bytes where all values are zero.

I tried running magickImage.Format = MagickFormat.Gray; immediately after loading the stream and the byte array is all zeros then as well.

Maybe I'm doing something wrong? The code is designed to take an image, convert it a 32 x 32 image, then gray with 1 byte per pixel.

Here's an example of the file I'm working with. Interestingly, it seems to work correctly on some files, but not others.
![Commision](https://user-images.githubusercontent.com/70203294/105724590-eb39f100-5f1f-11eb-87c7-886d5e234ceb.png)

I'm using Magick.NET-Q8-x64 7.23.1 and Magick.NET.SystemWindowsMedia 3.0.5

**Comment by dlemstra** [comment]
This is happening because you are using ` MagickFormat.Gray` instead of ` MagickFormat.Graya`. Your image contains transparency but the `RGB` values of that `RGBA` pixel are `000` (black). The alpha channel is ignored when you write the gray image and then only the RGB values are used and they are all zero. 

Your image has semi transarent pixels so it is not that easy to change it into 1 bit. You might want to ask for some help on the best way to get to two colors here: https://github.com/ImageMagick/ImageMagick/discussions.

**Comment by duckheadsoftware** [comment]
Thanks for the advice, I’ll ask.

 

Thanks, David

 

Don’t forget we have free versions of our software: Just search the App Store.

*	HEIC to JPEG, Pro, and Advanced editions
*	Duplicate Photo Cleaner
