### ISSUE TITLE
Where did PreserveCorruptImage go?

### ISSUE THREAD

**Issue by MichaelLogutov** [dlemstra/Magick.NET#9]
The latest version has removed PngReadDefines.PreserveCorruptImage property - why is that? I was using it to handle opening PNG images that has bad CRC but actually still can be viewed normally.

Also, where did ResolutionX and ResolutionY go? Why such breaking changes increments only the minor version of the package?

**Comment by dlemstra** [comment]
I removed PreserveCorruptImage because it only does this:
```c
if (image != (Image *) NULL)
  {
    const char
      *option;

    option=GetImageOption(image_info,"png:preserve-corrupt-image");
    if (IsStringTrue(option) == MagickFalse)
      image->columns=0;
  }
```
You could use this to disable preserving a corrupt image and I did not think anyone would need this. 

I changed ResolutionX and ResolutionY to density. Magick.NET is still alpha and I sometimes make breaking changes. You can find them here: https://github.com/dlemstra/Magick.NET/blob/master/Changes.md

ImagickMagick 7 will go out of beta very soon. I will probably move Magick.NET out of alpha then and don't make that many breaking changes. I don't increment the version number because I try to keep it the same as ImageMagick in the future and that is currently still at 7.0.0.0.

**Comment by MichaelLogutov** [comment]
I don't know if I can do that from my code (those variables looks internal to me). If I won't do that - will I still be able to read corrupted images?

**Comment by dlemstra** [comment]
The default behavior is that you can read corrupt images. That option could only be used to prevent you from being able to read corrupt images. Setting it to true in your old code did nothing.

**Comment by MichaelLogutov** [comment]
Ah, thanks for clarification. That piece of code that allowed to read corrupted images are critical to us - we've got quite a number of files that can be viewed perfectly but had something wrong in their CRC.
